import { mapType } from "./typemap";
import { type ASExport } from "./parser";
import { join, basename } from "path";
import { existsSync } from "fs";
import { createHash } from "crypto";

/**
 * Génère le contenu d'un fichier .d.ts à partir d'un tableau d'exports AS.
 * Si le contenu (hash) n'a pas changé, on n'écrase pas le fichier.
 *
 * @param exports     Liste des exports parsés
 * @param sourcePath  Chemin absolu vers le fichier `.as` d'origine
 */
export async function generateDts(
  exports: ASExport[],
  sourcePath: string,
): Promise<void> {
  const lines: string[] = [
    "// auto-generated by bun-plugin-assemblyscript — do not edit",
    "",
  ];

  for (const exp of exports) {
    if (exp.kind === "const") {
      lines.push(`export const ${exp.name}: ${mapType(exp.type!)};`);
    } else if (exp.kind === "function") {
      const params = exp
        .params!.map((p) => `${p.name}: ${mapType(p.type)}`)
        .join(", ");
      lines.push(
        `export function ${exp.name}(${params}): ${mapType(exp.returnType!)};`,
      );
    } else if (exp.kind === "class") {
      lines.push(`export class ${exp.name} {`);
      if (exp.methods) {
        for (const m of exp.methods) {
          const params = m
            .params!.map((p) => `${p.name}: ${mapType(p.type)}`)
            .join(", ");
          lines.push(`  ${m.name}(${params}): ${mapType(m.returnType!)};`);
        }
      }
      lines.push(`}`);
    }
  }

  const dtsContent = lines.join("\n") + "\n";
  const dtsPath = sourcePath + ".d.ts";
  const newHash = createHash("sha256").update(dtsContent).digest("hex");

  try {
    const existingContent = await Bun.file(dtsPath).text();
    const oldHash = createHash("sha256").update(existingContent).digest("hex");
    if (newHash === oldHash) {
      // Pas de modification structurelle de la signature, on ne fait rien
      return;
    }
  } catch (err) {
    // Fichier inexistant, on procède à l'écriture
  }

  await Bun.write(dtsPath, dtsContent);
}

/**
 * Génère ou met à jour un fichier de snippets VSCode pour les exports d'un fichier .as.
 */
export async function updateSnippets(
  exports: ASExport[],
  sourcePath: string,
): Promise<void> {
  const fileName = basename(sourcePath);
  const vscodeDir = join(process.cwd(), ".vscode");
  const snippetsPath = join(vscodeDir, "as-exports.code-snippets");

  if (!existsSync(vscodeDir)) return;

  let allSnippets: any = {};
  if (existsSync(snippetsPath)) {
    try {
      allSnippets = await Bun.file(snippetsPath).json();
    } catch (e) {}
  }

  // Supprimer les anciens snippets liés à ce fichier pour éviter les doublons
  for (const key in allSnippets) {
    if (key.includes(`(${fileName})`)) {
      delete allSnippets[key];
    }
  }

  // Ajouter les nouveaux snippets
  for (const exp of exports) {
    if (exp.kind === "function") {
      const params = exp
        .params!.map((p, i) => `\${${i + 1}:${p.name}}`)
        .join(", ");
      const snippetKey = `${exp.name} (${fileName})`;

      allSnippets[snippetKey] = {
        prefix: exp.name,
        scope: "typescript,javascript",
        body: [`${exp.name}(${params})`],
        description: `Appel de la fonction ${exp.name} depuis ${fileName} (retourne ${mapType(exp.returnType!)})`,
      };
    }
  }

  await Bun.write(snippetsPath, JSON.stringify(allSnippets, null, 2));
}
