import { mapType } from "./typemap";
import { type ASExport } from "./parser";

/**
 * Génère le contenu d'un fichier .d.ts à partir d'un tableau d'exports AS.
 * Si le contenu (hash) n'a pas changé, on n'écrase pas le fichier.
 *
 * @param exports     Liste des exports parsés
 * @param sourcePath  Chemin absolu vers le fichier `.as` d'origine
 */
export async function generateDts(
  exports: ASExport[],
  sourcePath: string
): Promise<void> {
  const lines: string[] = [
    "// auto-generated by bun-plugin-assemblyscript — do not edit",
    "",
  ];

  for (const exp of exports) {
    if (exp.kind === "const") {
      lines.push(`export const ${exp.name}: ${mapType(exp.type!)};`);
    } else if (exp.kind === "function") {
      const params = exp
        .params!.map((p) => `${p.name}: ${mapType(p.type)}`)
        .join(", ");
      lines.push(
        `export function ${exp.name}(${params}): ${mapType(exp.returnType!)};`
      );
    } else if (exp.kind === "class") {
      lines.push(`export class ${exp.name} {`);
      if (exp.methods) {
        for (const m of exp.methods) {
          const params = m
            .params!.map((p) => `${p.name}: ${mapType(p.type)}`)
            .join(", ");
          lines.push(
            `  ${m.name}(${params}): ${mapType(m.returnType!)};`
          );
        }
      }
      lines.push(`}`);
    }
  }

  const dtsContent = lines.join("\n") + "\n";
  const dtsPath = sourcePath + ".d.ts";
  const newHash = Bun.hash(dtsContent);

  try {
    const existingContent = await Bun.file(dtsPath).text();
    const oldHash = Bun.hash(existingContent);
    if (newHash === oldHash) {
      // Pas de modification structurelle de la signature, on ne fait rien
      return;
    }
  } catch (err) {
    // Fichier inexistant, on procède à l'écriture
  }

  await Bun.write(dtsPath, dtsContent);
}
