// auto-generated by bun-plugin-assemblyscript — do not edit

export function add(a: number, b: number): number;
export function multiply(a: number, b: number): number;
export function subtract(a: number, b: number): number;
export function texte(a: string): string;
