import type { BunPlugin } from "bun";
import { compile, type CompilerOptions } from "./compiler";
import { instantiate } from "./instantiator";
import { parseASExports, type ASExport } from "./typegen/parser";
import { generateDts } from "./typegen/generator";
import { join } from "path";
import { existsSync } from "fs";

export interface PluginOptions {
  compilerOverrides?: CompilerOptions;
}

function isBuildMode(build: { config?: { target?: string } }): boolean {
  return (
    build.config !== undefined &&
    typeof build.config.target === "string" &&
    build.config.target.length > 0 &&
    process.env.NODE_ENV === "production"
  );
}

function isComplexType(t: string): boolean {
  const trim = t.trim();
  return trim === "string" || trim === "String" || trim.includes("Array") || trim.includes("Map");
}

function hasComplexExports(exports: ASExport[]): boolean {
  for (const exp of exports) {
    if (exp.kind === "class") return true;
    if (exp.type && isComplexType(exp.type)) return true;
    if (exp.params && exp.params.some((p) => isComplexType(p.type))) return true;
    if (exp.returnType && isComplexType(exp.returnType)) return true;
    if (exp.methods && hasComplexExports(exp.methods)) return true;
  }
  return false;
}

function generateModule(exportNames: string[], parsedExports: ASExport[], wasmSource: string, isInline: boolean): string {
  const lines: string[] = [
    `// Auto-generated by bun-plugin-assemblyscript`,
  ];

  if (isInline) {
    lines.push(`const __b64 = ${JSON.stringify(wasmSource)};`);
    lines.push(`const __bin = Uint8Array.from(atob(__b64), (c) => c.charCodeAt(0));`);
  } else {
    lines.push(`const __url = ${JSON.stringify(wasmSource)};`);
    lines.push(`const __res = await fetch(__url);`);
    lines.push(`const __bin = new Uint8Array(await __res.arrayBuffer());`);
  }

  lines.push(
    `const __memory = new WebAssembly.Memory({ initial: 1 });`,
    `function __readStr(ptr) {`,
    `  if (!ptr) return "";`,
    `  const dv = new DataView(__memory.buffer);`,
    `  const len = dv.getInt32(ptr - 4, true) >>> 1;`,
    `  if (len <= 0) return "";`,
    `  return String.fromCharCode(...new Uint16Array(__memory.buffer, ptr, len));`,
    `}`,
    `function __writeStr(str) {`,
    `  if (str == null) return 0;`,
    `  const len = str.length;`,
    `  const ptr = __inst.exports.__new(len << 1, 1);`,
    `  const u16 = new Uint16Array(__memory.buffer, ptr, len);`,
    `  for (let i = 0; i < len; ++i) u16[i] = str.charCodeAt(i);`,
    `  return ptr;`,
    `}`,
    `const __imports = {`,
    `  env: {`,
    `    memory: __memory,`,
    `    abort(msg, file, line, col) {`,
    `      throw new Error(\`AbortError: \${__readStr(msg)} — \${__readStr(file)}:\${line}:\${col}\`);`,
    `    }`,
    `  }`,
    `};`,
    `const { instance: __inst } = await WebAssembly.instantiate(__bin, __imports);`
  );

  const exportedFns = new Set(exportNames);

  for (const exp of parsedExports) {
    if (exp.kind === "function" && exportedFns.has(exp.name)) {
      const isStringReturn = exp.returnType === "string" || exp.returnType === "String";
      const stringParams = exp.params?.map((p, i) => (p.type === "string" || p.type === "String" ? i : -1)).filter(i => i !== -1) || [];

      if (isStringReturn || stringParams.length > 0) {
        // Wrapper JS pour les strings
        const argsList = exp.params?.map(p => p.name).join(", ") || "";
        const wrappedArgs = exp.params?.map((p, i) => stringParams.includes(i) ? `__writeStr(${p.name})` : p.name).join(", ") || "";
        
        lines.push(`export const ${exp.name} = (${argsList}) => {`);
        lines.push(`  const res = __inst.exports.${exp.name}(${wrappedArgs});`);
        if (isStringReturn) {
          lines.push(`  return __readStr(res);`);
        } else {
          lines.push(`  return res;`);
        }
        lines.push(`};`);
      } else {
        lines.push(`export const ${exp.name} = __inst.exports.${exp.name};`);
      }
      exportedFns.delete(exp.name);
    }
  }

  // Exports restants (ex: constantes ou fonctions non parsées)
  for (const name of exportedFns) {
    if (name.startsWith("__")) continue; // ignorer les internes AS
    lines.push(`export const ${name} = __inst.exports.${name};`);
  }

  return lines.join("\n") + "\n";
}

export function assemblyScriptPlugin(options: PluginOptions = {}): BunPlugin {
  return {
    name: "bun-plugin-assemblyscript",
    async setup(build) {
      let embedMode = "auto";
      try {
        if (existsSync("bunfig.toml")) {
          const config = await Bun.file("bunfig.toml").text();
          const match = config.match(/embedMode\s*=\s*(?:"|')([^"']+)(?:"|')/);
          if (match) embedMode = match[1];
        }
      } catch (e) {}

      // Build context
      const isProd = isBuildMode(build) || process.env.NODE_ENV === "production" || build.config?.minify;

      build.onLoad({ filter: /\.as$/ }, async (args) => {
        let parsedExports: ASExport[] = [];
        let hasComplex = false;
        try {
          const source = await Bun.file(args.path).text();
          parsedExports = parseASExports(source);
          await generateDts(parsedExports, args.path);
          hasComplex = hasComplexExports(parsedExports);
        } catch (e) {
          console.warn("[bun-assemblyscript] Génération de types échouée :", e);
        }

        const compilerOptions: CompilerOptions = {
          optimizeLevel: isProd ? 3 : 0,
          shrinkLevel: isProd ? 2 : 0,
          runtime: hasComplex ? "incremental" : "stub",
          sourceMap: !isProd,
          debug: !isProd,
          ...options.compilerOverrides,
        };

        const result = await compile(args.path, compilerOptions);

        if (!result.success || !result.wasmBytes) {
          return {
            contents: "",
            errors: result.errors.map((text) => ({ text })),
          };
        }

        // Ecrire le sourcemap dans le cache à côté du .wasm si non prod
        if (!isProd && result.sourceMapBytes) {
          const cacheDir = join(process.cwd(), ".cache", "bun-as", require("path").basename(args.path));
          const currentHash = require("crypto").createHash("sha256").update(await Bun.file(args.path).text()).digest("hex");
          const mapPath = join(cacheDir, currentHash + ".wasm.map");
          try {
            await require("fs/promises").mkdir(cacheDir, { recursive: true });
            await Bun.write(mapPath, result.sourceMapBytes);
          } catch (e) {}
        }

        // Stratégie d'embedding
        let finalMode = embedMode;
        if (finalMode === "auto") {
          finalMode = result.wasmBytes.length < 100000 ? "inline" : "file";
        }

        const exportsMap = await instantiate(result.wasmBytes);
        const exportNames = Object.keys(exportsMap).filter(
          (k) => k !== "__data_end" && k !== "__heap_base"
        );

        if (finalMode === "inline") {
          const b64 = Buffer.from(result.wasmBytes).toString("base64");
          return { contents: generateModule(exportNames, parsedExports, b64, true), loader: "js" };
        } else {
          // File mode
          const outdir = build.config?.outdir || "./dist";
          const fileName = "module-" + Bun.hash(result.wasmBytes) + ".wasm";
          const outPath = join(process.cwd(), outdir, fileName);
          
          try {
            await require("fs/promises").mkdir(join(process.cwd(), outdir), { recursive: true });
            await Bun.write(outPath, result.wasmBytes);
          } catch(e) {}

          const wasmUrl = "./" + fileName;
          return { contents: generateModule(exportNames, parsedExports, wasmUrl, false), loader: "js" };
        }
      });
    },
  };
}
