import type { BunPlugin } from "bun";
import { compile, type CompilerOptions } from "./compiler";
import { instantiate } from "./instantiator";
import { parseASExports, type ASExport } from "./typegen/parser";
import { generateDts } from "./typegen/generator";
import { join } from "path";
import { existsSync } from "fs";

export interface PluginOptions {
  compilerOverrides?: CompilerOptions;
}

function isBuildMode(build: { config?: { target?: string } }): boolean {
  return (
    build.config !== undefined &&
    typeof build.config.target === "string" &&
    build.config.target.length > 0 &&
    process.env.NODE_ENV === "production"
  );
}

function isComplexType(t: string): boolean {
  const trim = t.trim();
  return trim === "string" || trim === "String" || trim.includes("Array") || trim.includes("Map");
}

function hasComplexExports(exports: ASExport[]): boolean {
  for (const exp of exports) {
    if (exp.kind === "class") return true;
    if (exp.type && isComplexType(exp.type)) return true;
    if (exp.params && exp.params.some((p) => isComplexType(p.type))) return true;
    if (exp.returnType && isComplexType(exp.returnType)) return true;
    if (exp.methods && hasComplexExports(exp.methods)) return true;
  }
  return false;
}

function generateInlineModule(exportNames: string[], wasmBase64: string): string {
  const lines: string[] = [
    `// Auto-generated by bun-plugin-assemblyscript (inline)`,
    `const __b64 = ${JSON.stringify(wasmBase64)};`,
    `const __bin = Uint8Array.from(atob(__b64), (c) => c.charCodeAt(0));`,
    `const __memory = new WebAssembly.Memory({ initial: 1 });`,
    `function __readStr(mem, ptr) {`,
    `  if (ptr === 0) return "";`,
    `  const dv = new DataView(mem.buffer);`,
    `  const len = dv.getInt32(ptr - 4, true) >>> 1;`,
    `  if (len <= 0) return "";`,
    `  return String.fromCharCode(...new Uint16Array(mem.buffer, ptr, len));`,
    `}`,
    `const __imports = {`,
    `  env: {`,
    `    memory: __memory,`,
    `    abort(msg, file, line, col) {`,
    `      const m = __readStr(__memory, msg);`,
    `      const f = __readStr(__memory, file);`,
    `      throw new Error(\`AbortError: \${m || "(no)"} — \${f}:\${line}:\${col}\`);`,
    `    }`,
    `  }`,
    `};`,
    `const { instance: __inst } = await WebAssembly.instantiate(__bin, __imports);`,
  ];
  for (const name of exportNames) {
    lines.push(`export const ${name} = __inst.exports.${name};`);
  }
  return lines.join("\n") + "\n";
}

function generateFileModule(exportNames: string[], wasmUrl: string): string {
  const lines: string[] = [
    `// Auto-generated by bun-plugin-assemblyscript (file)`,
    `const __url = ${JSON.stringify(wasmUrl)};`,
    `const __res = await fetch(__url);`,
    `const __bin = new Uint8Array(await __res.arrayBuffer());`,
    `const __memory = new WebAssembly.Memory({ initial: 1 });`,
    `function __readStr(mem, ptr) {`,
    `  if (ptr === 0) return "";`,
    `  const dv = new DataView(mem.buffer);`,
    `  const len = dv.getInt32(ptr - 4, true) >>> 1;`,
    `  if (len <= 0) return "";`,
    `  return String.fromCharCode(...new Uint16Array(mem.buffer, ptr, len));`,
    `}`,
    `const __imports = {`,
    `  env: {`,
    `    memory: __memory,`,
    `    abort(msg, file, line, col) {`,
    `      const m = __readStr(__memory, msg);`,
    `      const f = __readStr(__memory, file);`,
    `      throw new Error(\`AbortError: \${m || "(no)"} — \${f}:\${line}:\${col}\`);`,
    `    }`,
    `  }`,
    `};`,
    `const { instance: __inst } = await WebAssembly.instantiate(__bin, __imports);`,
  ];
  for (const name of exportNames) {
    lines.push(`export const ${name} = __inst.exports.${name};`);
  }
  return lines.join("\n") + "\n";
}

export function assemblyScriptPlugin(options: PluginOptions = {}): BunPlugin {
  return {
    name: "bun-plugin-assemblyscript",
    async setup(build) {
      let embedMode = "auto";
      try {
        if (existsSync("bunfig.toml")) {
          const config = await Bun.file("bunfig.toml").text();
          const match = config.match(/embedMode\s*=\s*(?:"|')([^"']+)(?:"|')/);
          if (match) embedMode = match[1];
        }
      } catch (e) {}

      // Build context
      const isProd = isBuildMode(build) || process.env.NODE_ENV === "production" || build.config?.minify;

      build.onLoad({ filter: /\.as$/ }, async (args) => {
        let parsedExports: ASExport[] = [];
        let hasComplex = false;
        try {
          const source = await Bun.file(args.path).text();
          parsedExports = parseASExports(source);
          await generateDts(parsedExports, args.path);
          hasComplex = hasComplexExports(parsedExports);
        } catch (e) {
          console.warn("[bun-assemblyscript] Génération de types échouée :", e);
        }

        const compilerOptions: CompilerOptions = {
          optimizeLevel: isProd ? 3 : 0,
          shrinkLevel: isProd ? 2 : 0,
          runtime: hasComplex ? "incremental" : "stub",
          sourceMap: !isProd,
          debug: !isProd,
          ...options.compilerOverrides,
        };

        const result = await compile(args.path, compilerOptions);

        if (!result.success || !result.wasmBytes) {
          return {
            contents: "",
            errors: result.errors.map((text) => ({ text })),
          };
        }

        // Ecrire le sourcemap dans le cache à côté du .wasm si non prod
        if (!isProd && result.sourceMapBytes) {
          const cacheDir = join(process.cwd(), ".cache", "bun-as", require("path").basename(args.path));
          const currentHash = require("crypto").createHash("sha256").update(await Bun.file(args.path).text()).digest("hex");
          const mapPath = join(cacheDir, currentHash + ".wasm.map");
          try {
            await require("fs/promises").mkdir(cacheDir, { recursive: true });
            await Bun.write(mapPath, result.sourceMapBytes);
          } catch (e) {}
        }

        // Stratégie d'embedding
        let finalMode = embedMode;
        if (finalMode === "auto") {
          finalMode = result.wasmBytes.length < 100000 ? "inline" : "file";
        }

        const exportsMap = await instantiate(result.wasmBytes);
        const exportNames = Object.keys(exportsMap).filter(
          (k) => k !== "__data_end" && k !== "__heap_base"
        );

        if (finalMode === "inline") {
          const b64 = Buffer.from(result.wasmBytes).toString("base64");
          return { contents: generateInlineModule(exportNames, b64), loader: "js" };
        } else {
          // File mode
          const outdir = build.config?.outdir || "./dist";
          const fileName = "module-" + Bun.hash(result.wasmBytes) + ".wasm";
          const outPath = join(process.cwd(), outdir, fileName);
          
          try {
            await require("fs/promises").mkdir(join(process.cwd(), outdir), { recursive: true });
            await Bun.write(outPath, result.wasmBytes);
          } catch(e) {}

          const wasmUrl = "./" + fileName;
          return { contents: generateFileModule(exportNames, wasmUrl), loader: "js" };
        }
      });
    },
  };
}
